// <auto-generated />
using System;
using Identity.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Identity.Domain.Entities.InsurancePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsuranceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValidMemberIdPattern")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("InsuranceName")
                        .IsUnique()
                        .HasDatabaseName("IX_InsurancePlan_InsuranceName");

                    b.ToTable("InsurancePlans", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            InsuranceName = "Blue Cross Blue Shield",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValidMemberIdPattern = "^[A-Z]{3}\\d{9}$"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            InsuranceName = "Aetna",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValidMemberIdPattern = "^\\d{8,12}$"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0003-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            InsuranceName = "UnitedHealthcare",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValidMemberIdPattern = "^U\\d{9}$"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0004-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            InsuranceName = "Cigna",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValidMemberIdPattern = "^\\d{10}$"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0005-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            InsuranceName = "Humana",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValidMemberIdPattern = "^H\\d{8}$"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0006-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            InsuranceName = "Kaiser Permanente",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValidMemberIdPattern = "^\\d{8,10}$"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0007-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            InsuranceName = "Anthem",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValidMemberIdPattern = "^[A-Z]{2}\\d{9}$"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0008-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            InsuranceName = "Molina Healthcare",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValidMemberIdPattern = "^\\d{9,12}$"
                        });
                });

            modelBuilder.Entity("Identity.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InsurancePolicyNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InsuranceProvider")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IntakeCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Patient_UserId");

                    b.ToTable("Patients", "identity");
                });

            modelBuilder.Entity("Identity.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshToken_Token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshToken_UserId");

                    b.ToTable("RefreshTokens", "identity");
                });

            modelBuilder.Entity("Identity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_User_Email");

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("Identity.Domain.Entities.Patient", b =>
                {
                    b.HasOne("Identity.Domain.Entities.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("Identity.Domain.Entities.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Identity.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Identity.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Identity.Domain.Entities.User", b =>
                {
                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
