// <auto-generated />
using System;
using Clinical.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clinical.Infrastructure.Migrations
{
    [DbContext(typeof(ClinicalDbContext))]
    [Migration("20260419113445_V004_IntegrityConstraints")]
    partial class V004_IntegrityConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("clinical")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clinical.Domain.Entities.ClinicalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EncryptedFilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessingError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_ClinicalDocument_PatientId");

                    b.ToTable("ClinicalDocuments", "clinical");
                });

            modelBuilder.Entity("Clinical.Domain.Entities.DataConflict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConflictingDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConflictingValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResolutionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("SourceDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("StaffNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConflictingDocumentId");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_DataConflict_PatientId");

                    b.HasIndex("SourceDocumentId");

                    b.HasIndex("PatientId", "ResolutionStatus")
                        .HasDatabaseName("IX_DataConflict_Patient_Status");

                    b.ToTable("DataConflicts", "clinical");
                });

            modelBuilder.Entity("Clinical.Domain.Entities.DocumentEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("int");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmbeddingVector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VectorDimension")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "ChunkIndex")
                        .IsUnique()
                        .HasDatabaseName("IX_DocumentEmbedding_Document_Chunk");

                    b.ToTable("DocumentEmbeddings", "clinical");
                });

            modelBuilder.Entity("Clinical.Domain.Entities.ExtractedData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SourcePage")
                        .HasColumnType("int");

                    b.Property<string>("SourceText")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_ExtractedData_PatientId");

                    b.HasIndex("DocumentId", "Category")
                        .HasDatabaseName("IX_ExtractedData_Document_Category");

                    b.ToTable("ExtractedData", "clinical", t =>
                        {
                            t.HasCheckConstraint("CK_ExtractedData_ConfidenceScore", "[ConfidenceScore] >= 0.0 AND [ConfidenceScore] <= 1.0");
                        });
                });

            modelBuilder.Entity("Clinical.Domain.Entities.MedicalCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodeType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExtractedDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ExtractedDataId");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_MedicalCode_PatientId");

                    b.HasIndex("PatientId", "CodeType", "Code")
                        .HasDatabaseName("IX_MedicalCode_Patient_Type_Code");

                    b.ToTable("MedicalCodes", "clinical");
                });

            modelBuilder.Entity("Clinical.Domain.Entities.PatientView360", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnoses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LabResults")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastRefreshedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicalHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique()
                        .HasDatabaseName("IX_PatientView360_PatientId");

                    b.ToTable("PatientViews360", "clinical");
                });

            modelBuilder.Entity("SharedKernel.Domain.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AfterState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("IX_AuditLog_ActorId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AuditLog_Timestamp");

                    b.HasIndex("Resource", "ResourceId")
                        .HasDatabaseName("IX_AuditLog_Resource");

                    b.ToTable("AuditLogs", "clinical");
                });

            modelBuilder.Entity("Clinical.Domain.Entities.DataConflict", b =>
                {
                    b.HasOne("Clinical.Domain.Entities.ClinicalDocument", "ConflictingDocument")
                        .WithMany()
                        .HasForeignKey("ConflictingDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Clinical.Domain.Entities.ClinicalDocument", "SourceDocument")
                        .WithMany()
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ConflictingDocument");

                    b.Navigation("SourceDocument");
                });

            modelBuilder.Entity("Clinical.Domain.Entities.DocumentEmbedding", b =>
                {
                    b.HasOne("Clinical.Domain.Entities.ClinicalDocument", "Document")
                        .WithMany("Embeddings")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Clinical.Domain.Entities.ExtractedData", b =>
                {
                    b.HasOne("Clinical.Domain.Entities.ClinicalDocument", "Document")
                        .WithMany("ExtractedDataPoints")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Clinical.Domain.Entities.MedicalCode", b =>
                {
                    b.HasOne("Clinical.Domain.Entities.ClinicalDocument", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Clinical.Domain.Entities.ExtractedData", "ExtractedData")
                        .WithMany()
                        .HasForeignKey("ExtractedDataId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Document");

                    b.Navigation("ExtractedData");
                });

            modelBuilder.Entity("Clinical.Domain.Entities.PatientView360", b =>
                {
                    b.OwnsOne("Clinical.Domain.Entities.PatientVitals", "Vitals", b1 =>
                        {
                            b1.Property<Guid>("PatientView360Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BloodPressure")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double?>("HeartRate")
                                .HasColumnType("float");

                            b1.Property<double?>("Height")
                                .HasColumnType("float");

                            b1.Property<DateTime?>("RecordedAt")
                                .HasColumnType("datetime2");

                            b1.Property<double?>("Temperature")
                                .HasColumnType("float");

                            b1.Property<double?>("Weight")
                                .HasColumnType("float");

                            b1.HasKey("PatientView360Id");

                            b1.ToTable("PatientViews360", "clinical");

                            b1.ToJson("Vitals");

                            b1.WithOwner()
                                .HasForeignKey("PatientView360Id");
                        });

                    b.Navigation("Vitals");
                });

            modelBuilder.Entity("Clinical.Domain.Entities.ClinicalDocument", b =>
                {
                    b.Navigation("Embeddings");

                    b.Navigation("ExtractedDataPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
